post_install() {
    echo ">>> leJOS was designed to be run on Sun Java 1.5 or newer.  While this"
    echo ">>> package allows other JDKs and JVMs, you may experience problems."
    echo ">>> If leJOS does not work correctly, please use Sun Java."
    echo ">>>"
    echo ">>> For samples of usage and documentation please visit "
    echo ">>> 'http://lejos.sourceforge.net/'."
}

post_upgrade() {
    post_install
}
